version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
  
image: Windows
  
configuration: Release
    
install:
- cmd/dasda git submodule update --init --recursive
asdasdasdas
before_build:
- cmd: echo Current Directory:
- cmd: cd
- dir
- cmd: dir Cinecoder.Samples.sln
- cmd: nuget restore
build_script:
#- cmd: MSBuild C:\Users\appveyor\projects\cinecoder-samples\Cinecoder.Samples.sln /p:Configuration=Release /p:Platform=x64
- cmd: cd
test_script:
- cmd: nunit3-console _bin\Release.x64\Daniel2.Managed.Tests.dll --result=myresults.xml;format=AppVeyor

after_build:
- cmd: >-
    7z a CinecoderSamples-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\_bin\Release.x64 %APPVEYOR_BUILD_FOLDER%\_bin\Release.ARM64
    
    appveyor PushArtifact CinecoderSamples-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip
