version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
    - master
    
build:
  project: Cinecoder.Samples.sln
  
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Windows
      platform: x64
      job_name: Build on Windows x64
    
configuration: Release
    
install:
- cmd: git submodule update --init --recursive
before_build:
- dir
- cmd: dir Cinecoder.Samples.sln
- cmd: nuget restore
build_script:
- cmd: MSBuild Cinecoder.Samples.sln /p:Configuration=Release /p:Platform=x64
- cmd: MSBuild Cinecoder.Samples.sln /p:Configuration=Release /p:Platform=ARM64
test_script:
- cmd: nunit3-console _bin\Release.x64\Daniel2.Managed.Tests.dll --result=myresults.xml;format=AppVeyor

after_build:
- cmd: >-
    7z a CinecoderSamples-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\_bin\Release.x64 %APPVEYOR_BUILD_FOLDER%\_bin\Release.ARM64
    
    appveyor PushArtifact CinecoderSamples-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip
